name: dash_kit_core
description: The core component for DashKit that provides basic architecture components
version: 3.0.3
homepage: https://github.com/Dash-Kit/dash-kit-core

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async_redux: ^14.1.4
  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.16.5

flutter:
